### PR TITLE
Attempt to extend cookie expiration

### PR DESCRIPTION
**Pull request by etriebe**

### CODE REVIEW

**Comment by etriebe** [comment]
This appears working for me. It removed the login prompts every few minutes when using extenral authentication.

**Comment by etriebe** [comment]
@toiyabe Can you review? No rush as I have this deployed with local nuget package.

**Comment by toiyabe** [comment]
Hi Eric, sure can this evening. I’m on the road in Chicago but will be back online tonight
Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by toiyabe** [comment]
Eric,
Would you mind if I make you an admin on this repo so you can approve things?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by etriebe** [comment]
Totally fine with me! Just let me know what sorts of things you'd want me
to do and I'll just stick to that (e.g. just approve but not release a new
version of the nuget package).

**Comment by toiyabe** [comment]
Thanks Eric! I can really use the help. I have multiple projects going on. This evening I’ll see you up.
Thanks!!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by toiyabe** [comment]
Hello Eric,
Check your email for an invite to the project.
Also, all unit tests passing (cool!) and the nuget package is pushed.
Next week would you like to connect via Teams or Zoom?
Thanks for everything!!!!!!
-Eric

**Comment by etriebe** [comment]
Yeah, happy to chat! Send me an email.

**Comment by toiyabe** [comment]
Hello Eric, I sent you an email. Let me know if you didn't get it.
Thanks!

**Pull request merged**
