### PR TITLE
Support generic entity keys

### PR DESCRIPTION
**Pull request by vadim-kor**
Added support of generic TKey. Updated tests to test the current project instead of the version published on nuget.

### CODE REVIEW

**Comment by toiyabe** [comment]
Hello vadim-kor, 
Thank you for the pull request, I'm working on the review right now.
Thank you!!
-Eric

**Review by toiyabe — COMMENTED** [review]
Question, for backward compatibility, would this break existing applications?  Perhaps rather than require a `string` perhaps add the ability to handle a generic key, while making an override to allow the method signature below?  Perhaps something like below:

Option 1:
`
builder.Services.AddCosmosIdentity<ApplicationDbContext, IdentityUser, IdentityRole>(...)
`

Option 2:
`
builder.Services.AddCosmosIdentity<ApplicationDbContext, IdentityUser, IdentityRole, string>(...)
`

Thoughts?

**Comment by johnkwaters** [comment]
Hi - I also need the overload that can handle TKey. In fact, my code uses the full set of tables

        IdentityDbContext<
            ApplicationUser,
            ApplicationRole,
            int,
            IdentityUserClaim<int>,
            ApplicationUserRole,
            IdentityUserLogin<int>,
            IdentityRoleClaim<int>,
            IdentityUserToken<int>

But I might be able to get by with just the first 2 if they support the IdentityUser<TKey> etc

**Comment by adambarath** [comment]
Is there any update on this one?

It may solves this issue: https://github.com/MoonriseSoftwareCalifornia/AspNetCore.Identity.CosmosDb/issues/14

**Comment by toiyabe** [comment]
Hello @vadim-kor, I have merged your code in a later version that is refactored for .Net 8.  It is passing all unit tests, which is terrifc.  Thank you so much for your hard work!

**Pull request closed without merging**
